### ISSUE TITLE
cannot unmarshal object into Go struct field Calendar.payload.usersPermittedToEdit of type string

### ISSUE THREAD

**Issue by beorereleverion** [essentialkaos/go-confluence#29]
### Bug report

**System info:**

* **Go Version (`go version`):1.16** 

**Steps to reproduce:**

1. User must can read calendar, but must has not right to write this
2. use api.GetCalendars functions
3. 

**Expected behavior:**

unmarshalled calendar

**Actual behavior:**

received err: json: cannot unmarshal object into Go struct field Calendar.payload.usersPermittedToEdit of type string

**Comment by andyone** [comment]
Hi! Thanks for your report.

I have released version `5.1.1` (#30) with the fix for this issue.
